on:
  pull_request:
  push:
    branches: master

name: Continuous integration

jobs:
  analyze:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main
    with:
      clippy_default: false
      clippy_args: --features=rkyv/size_32

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  build_benches:
    name: Build Benchmarks
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: cargo bench --no-run

  run_examples:
    name: Run Examples
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: cargo run --release --example circuit

  build_docs:
    name: Build Documentation
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: make doc
      - run: make doc-internal

  build_no_std:
    name: Build no_std
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: make no-std
      - run: cargo check --target thumbv6m-none-eabi --no-default-features --features alloc,rkyv-impl,rkyv/size_32

  test:
    name: Tests
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: make test

  coverage:
    name: Coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt install -y kcov
      - run: RUSTFLAGS='-Cdebuginfo=2 -Cllvm-args=--inline-threshold=0 -Clink-dead-code' cargo test --release --no-run --all-features
      - name: Collect coverage
        run: >
          find target/release/deps -type f -executable ! -name "*.*" |
          xargs -n1 kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  cargo_deny:
    name: Cargo Deny
    uses: dusk-network/.github/.github/workflows/cargo-deny.yml@f6d992d53d414c1b224d4fd5a8e8f9d40017115e
    with:
      runner: ubuntu-22.04
      rust-toolchain: "1.96.1"
      cargo-deny-version: "0.20.2"
      enable_sccache: false
