on:
  pull_request:
  push:
    branches: master

name: Continuous integration

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  analyze:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main
    with:
      clippy_default: false
      clippy_args: --features=rkyv/size_32

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  build_benches:
    name: Build Benchmarks
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: cargo bench --no-run

  run_examples:
    name: Run Examples
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: cargo run --release --example circuit

  build_docs:
    name: Build Documentation
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: make doc
      - run: make doc-internal

  build_no_std:
    name: Build no_std
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: make no-std
      - run: cargo check --target thumbv6m-none-eabi --no-default-features --features alloc,rkyv-impl,rkyv/size_32

  test:
    name: Tests
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: make test
